--IN ORDER TO PERFORM MERGE OPERATION WE NEED TO CREATE TARGET TABLE

CREATE TABLE EMPLOYEES_TRG
AS
SELECT *FROM EMPLOYEES
WHERE 1=2;

SELECT *
FROM EMPLOYEES;------------------>SOURCE TABLE


SELECT *
FROM EMPLOYEES_TRG;------------->TARGET TABLE

---WE NEED TO MERGE DATA FROM SOURCE TABLE INTO TARGET ,RIGHT 
---SO HERE IS SYNTAX

--SCENARIO ------------->UPDATE INSERT
MERGE INTO EMPLOYEES_TRG  ETRG
USING EMPLOYEES  ESRC
ON (ESRC.EID=ETRG.EID)
WHEN MATCHED THEN UPDATE
SET 
    ETRG.FNAME=ESRC.FNAME,
    ETRG.SALARY=ESRC.SALARY,
    ETRG.DID=ESRC.DID
WHEN NOT MATCHED THEN
INSERT (EID,FNAME,SALARY,DID)
VALUES(ESRC.EID,ESRC.FNAME,ESRC.SALARY,ESRC.DID);
--HERE WE GO,ALL 7 ROWS MERGED.
COMMIT;

--IF INSERT ONE ROW IN SOURCE TABLE AND UPDATE ONE ROW IN SOURCE TABLE
INSERT INTO EMPLOYEES VALUES(8,'Rana','750',20);
INSERT INTO EMPLOYEES VALUES(9,'Tejaswi','850',30);
UPDATE EMPLOYEES SET SALARY=420 WHERE EID=4;

    
--THEN AGAIN GO TO MERGE QUERY AND EXECUTE IT.    



--=====================================================================
--SCENARIO ------------->DELETE INSERT
MERGE INTO EMPLOYEES_TRG  ETRG
USING EMPLOYEES ESRC
ON (ETRG.EID=ESRC.EID)
WHEN MATCHED THEN UPDATE  
SET
    ETRG.ENAME=ESRC.ENAME,
    ETRG.SALARY=ESRC.SALARY,
    ETRG.DID=ESRC.DID
WHEN NOT MATCHED THEN 
INSERT (EID,ENAME,SALARY,DID) VALUES(ESRC.EID,ESRC.ENAME,ESRC.SALARY,ESRC.DID)
DELETE FROM EMPLOYEES_TRG ETRG
WHERE NOT EXISTS (
  SELECT 1
  FROM EMPLOYEES ESRC
  WHERE ETRG.EID = ESRC.EID
);


 
 --=========================================================
 --INSERT DELETE SCENARIO
MERGE INTO EMPLOYEES_TRG ETRG
USING EMPLOYEES SRC
ON (ETRG.EID=SRC.EID)
WHEN MATCHED THEN
 DELETE 
  WHERE 1=1
WHEN NOT MATCHED THEN
INSERT (EID,FNAME,SALARY,DID) VALUES(SRC.EID,SRC.FNAME,SRC.SALARY,SRC.DID);



--==============================================================================
SELECT *FROM EMPLOYEES;
INSERT INTO EMPLOYEES



-------------------------------------------------------------------------------------
--UPDATE-INSERT SCENARIO  --->'Upsert'
MERGE INTO TRG_TABLE trg           ---------merge into target table
USING SRC_TABLE  src               ---------using source table
ON (trg=src)                        --------based on certain condition
WHEN MATCHED THEN UPDATE             -------When matched than  update
SET                                  
    trg.FNAME=src.FNAME,
WHEN NOT MATCHED THEN               --------When not matched than insert 
INSERT ()
VALUES(src);


